name: Docker Image CI

on:
  release

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.1.0
      
    - name: Build the Docker image
      run: docker build . -t donate-api -t ${{ secrets.DOCKERHUB_USERNAME }}/donate-api:${{ steps.latest_version.outputs.latest_tag }}
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/donate-api
